version: '3.8'

services:
  web:
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_crud:fastapi_crud@db/fastapi_crud
  db:
    image: postgres:15.1-alpine
    volumes:
      - /var/lib/docker/volumes/fastapi-crud-pgsql/_data:/var/lib/postgresql/data/
    ports:
      - 5430:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_crud
      - POSTGRES_PASSWORD=fastapi_crud
      - POSTGRES_DB=fastapi_crud

volumes:
  postgres_data: